# The main config file for your Jekyll template

# Site settings
title: Probably a bad idea # used for the html title of every page
desc: >
    A blog by Gabe Albacarys, a full-time software engineer and part-time
    dreamer. Almost certainly full of bad advice, worse explanations, and 
    untold amounts of self-indulgent musing.

url: http://galbacarys.github.io # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: g.albacarys@gmail.com
author: gabe albacarys
twitter_username: itsgabethebando
github_username: galbacarys
github_source: galbacarys.github.io

# Put your ga tracking code below
google_analytics: 'UA-97908556-1'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Articles
    url: /articles/
    desc: Stuff I write about
  - title: Projects
    url: /projects/
    desc: Stuff I do
  - title: Work
    url: /work/
    desc: Stuff I'm paid to do
  - title: About
    url: /about/
    desc: Blatant lies about myself

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

